import type { ProviderId } from "@/content/locations/providers";

export type SiteExtra = "meetingRooms" | "parcels";

export type Site = {
  /** URL path under /virtual-offices/, e.g. "manchester" or "london/mayfair". */
  path: string;
  /** Portal onboarding plan id (the `plan` query param). */
  plan: string;
  /** Short label used in menus, cards and breadcrumbs. */
  label: string;
  city: string;
  building?: string;
  street: string;
  /** Locality line, e.g. "City Centre, Manchester, M4". */
  area: string;
  priceFrom: number;
  /** Registered office add-on price for this address. */
  registeredFrom: number;
  image: string;
  imageAlt: string;
  extras?: SiteExtra[];
  /** Competitor monthly prices shown in the comparison table. */
  competitors: Partial<Record<ProviderId, number>>;
};

const regional = { virtualHq: 25, orega: 42, regus: 52 } as const;
const prime = { virtualHq: 60, regus: 189, servcorp: 255 } as const;

export const sites: Site[] = [
  {
    path: "london/london-central",
    plan: "london_fitzrovia",
    label: "Central London",
    city: "London",
    street: "Fitzroy Street",
    area: "Fitzrovia, London, W1T",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/fitzrovia.webp",
    imageAlt: "Our central London office building in Fitzrovia",
    competitors: prime,
  },
  {
    path: "london/mayfair",
    plan: "london_mayfair",
    label: "Mayfair",
    city: "London",
    street: "Albemarle Street",
    area: "Mayfair, London, W1S",
    priceFrom: 16,
    registeredFrom: 17,
    image: "/locations/mayfair.webp",
    imageAlt: "Office building on Albemarle Street, Mayfair",
    extras: ["meetingRooms"],
    competitors: prime,
  },
  {
    path: "london/the-city-london",
    plan: "london_farringdon",
    label: "The City",
    city: "London",
    street: "Coldbath Square",
    area: "Farringdon, London, EC1R",
    priceFrom: 14,
    registeredFrom: 17,
    image: "/locations/the-city-london.jpg",
    imageAlt: "Office building on Coldbath Square, Farringdon",
    competitors: prime,
  },
  {
    path: "london/london-bridge",
    plan: "london_bridge",
    label: "London Bridge",
    city: "London",
    street: "Lombard Street",
    area: "Near London Bridge, EC3V",
    priceFrom: 14,
    registeredFrom: 21,
    image: "/locations/lombard-street.jpg",
    imageAlt: "Office building on Lombard Street near London Bridge",
    competitors: prime,
  },
  {
    path: "manchester",
    plan: "manchester_city_centre",
    label: "Manchester",
    city: "Manchester",
    building: "Swan Buildings",
    street: "Swan Street",
    area: "City Centre, Manchester, M4",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/manchester.webp",
    imageAlt: "Swan Buildings on Swan Street, Manchester",
    competitors: { virtualHq: 30, orega: 42, regus: 52 },
  },
  {
    path: "birmingham",
    plan: "birmingham_regent_place",
    label: "Birmingham",
    city: "Birmingham",
    building: "Izabella House",
    street: "Regent Place",
    area: "City Centre, Birmingham, B1",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/birmingham.webp",
    imageAlt: "Izabella House on Regent Place, Birmingham",
    competitors: regional,
  },
  {
    path: "leeds",
    plan: "leeds_radley_house",
    label: "Leeds",
    city: "Leeds",
    building: "Radley House",
    street: "Richardshaw Road",
    area: "Leeds, LS28",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/leeds.jpg",
    imageAlt: "Radley House on Richardshaw Road, Leeds",
    extras: ["meetingRooms"],
    competitors: { virtualHq: 40, orega: 42, regus: 52 },
  },
  {
    path: "bradford",
    plan: "bradford_latitude",
    label: "Bradford",
    city: "Bradford",
    building: "Latitude",
    street: "The Interchange, Nelson Street",
    area: "Bradford, BD1",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/bradford.jpg",
    imageAlt: "Latitude building at The Interchange, Bradford",
    competitors: regional,
  },
  {
    path: "huddersfield",
    plan: "huddersfield_st_peters_street",
    label: "Huddersfield",
    city: "Huddersfield",
    building: "Station Street Buildings",
    street: "St Peter's Street",
    area: "Huddersfield, HD1",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/huddersfield.jpg",
    imageAlt: "Station Street Buildings, Huddersfield",
    competitors: regional,
  },
  {
    path: "liverpool",
    plan: "liverpool_jamaica_street",
    label: "Liverpool",
    city: "Liverpool",
    building: "Basecamp",
    street: "Jamaica Street",
    area: "Liverpool, L1",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/liverpool.jpg",
    imageAlt: "Basecamp building on Jamaica Street, Liverpool",
    competitors: { virtualHq: 40, orega: 42, regus: 52 },
  },
  {
    path: "edinburgh",
    plan: "edinburgh_new_town",
    label: "Edinburgh",
    city: "Edinburgh",
    street: "Hill Street",
    area: "New Town, Edinburgh, EH1",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/edinburgh.jpg",
    imageAlt: "Georgian office building on Hill Street, Edinburgh",
    competitors: { virtualHq: 35, cityOffice: 49.84, regus: 52 },
  },
  {
    path: "glasgow/newton-place",
    plan: "glasgow_newton_place",
    label: "Newton Place",
    city: "Glasgow",
    building: "Technology House",
    street: "Newton Place",
    area: "Glasgow, G3",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/newton-place.jpg",
    imageAlt: "Technology House on Newton Place, Glasgow",
    competitors: { virtualHq: 30, orega: 42, regus: 52 },
  },
  {
    path: "glasgow/west-george-street",
    plan: "glasgow_west_george_street",
    label: "West George Street",
    city: "Glasgow",
    street: "West George Street",
    area: "Glasgow, G2",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/west-george-street.jpg",
    imageAlt: "Office building on West George Street, Glasgow",
    extras: ["meetingRooms", "parcels"],
    competitors: { virtualHq: 30, orega: 42, regus: 52 },
  },
  {
    path: "cardiff",
    plan: "cardiff_city_centre",
    label: "Cardiff",
    city: "Cardiff",
    street: "Museum Place",
    area: "City Centre, Cardiff, CF10",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/cardiff.jpg",
    imageAlt: "Office building on Museum Place, Cardiff",
    competitors: { virtualHq: 25, regus: 33, rombourne: 35 },
  },
  {
    path: "belfast",
    plan: "belfast_gallery",
    label: "Belfast",
    city: "Belfast",
    building: "Gallery Building",
    street: "Dublin Road",
    area: "Belfast, BT2",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/belfast.jpg",
    imageAlt: "The Gallery Building on Dublin Road, Belfast",
    competitors: { virtualHq: 30, orega: 42, regus: 52 },
  },
  {
    path: "newcastle-upon-tyne",
    plan: "newcastle_collingwood_street",
    label: "Newcastle",
    city: "Newcastle upon Tyne",
    building: "Collingwood Buildings",
    street: "Collingwood Street",
    area: "Newcastle, NE1",
    priceFrom: 10,
    registeredFrom: 17,
    image: "/locations/newcastle-upon-tyne.jpg",
    imageAlt: "Collingwood Buildings on Collingwood Street, Newcastle",
    extras: ["meetingRooms"],
    competitors: { virtualHq: 35, regus: 85 },
  },
  {
    path: "bristol/st-nicholas-street",
    plan: "bristol_st_nicholas_st",
    label: "St Nicholas Street",
    city: "Bristol",
    building: "The Old Stock Exchange",
    street: "St Nicholas Street",
    area: "Bristol, BS1",
    priceFrom: 15,
    registeredFrom: 21,
    image: "/locations/st-nicholas-street.jpg",
    imageAlt: "The Old Stock Exchange on St Nicholas Street, Bristol",
    competitors: { virtualHq: 30, rombourne: 35, orega: 42 },
  },
  {
    path: "bristol/whiteladies-road-clifton",
    plan: "bristol_clifton",
    label: "Clifton",
    city: "Bristol",
    street: "Whiteladies Road",
    area: "Clifton, Bristol, BS8",
    priceFrom: 35,
    registeredFrom: 21,
    image: "/locations/whiteladies-road-clifton.jpg",
    imageAlt: "Office building on Whiteladies Road, Clifton",
    competitors: { virtualHq: 30, rombourne: 35, orega: 42 },
  },
  {
    path: "newmarket",
    plan: "cambridge_city_centre",
    label: "Cambridge",
    city: "Newmarket",
    street: "3 The Avenue",
    area: "Newmarket, CB8",
    priceFrom: 16,
    registeredFrom: 17,
    image: "/locations/newmarket.png",
    imageAlt: "Our Newmarket office near Cambridge",
    competitors: { virtualHq: 45, allia: 40, regus: 79 },
  },
];
